// Locale dict for the room UI. Loaded by RoomTerminal.tsx based on the
// room's `locale` column (fixed at creation time, so every participant sees
// the same prompts regardless of their browser language). The shape mirrors
// the main terminal's i18n: flat key/value with {placeholder} tokens.
//
// All keys live here (not in /src/i18n/{en,es,pt}.json) so the room
// translations evolve independently from the main terminal's dict.

import type { Locale } from "./types";

export type RoomDict = Record<string, string>;

const EN: RoomDict = {
  "title": "room",
  "subtitle": "collaborative brainstorm",
  "loading": "loading room…",
  "not_found": "room not found or expired.",
  "back_to_main": "← back to /",
  "expired": "this room expired. start a new one with `room create`.",
  "missing_env": "supabase env missing; rooms are not configured.",

  "onboard.heading": "pick a handle to enter the room.",
  "onboard.handle_prompt": "handle (e.g. @aiponce): ",
  "onboard.handle_invalid": "handle must be 2-32 chars, letters/numbers/_-",
  "onboard.handle_taken": "that handle is already in use. try another.",
  "onboard.cta": "join",
  "onboard.share": "share this link with your team: {url}",

  "status.phase": "phase: {phase}",
  "status.live": "● live",
  "status.reconnecting": "○ reconnecting…",
  "status.expires_in": "expires in {mins}m",
  "status.quorum": "{ready}/{total} ready",
  "status.host": "host",
  "status.expires_soon": "this room expires in less than 15 minutes.",

  "stream.welcome": "welcome, {handle}. type `help` to see commands.",
  "stream.joined": "{handle} joined.",
  "stream.left": "{handle} left.",
  "stream.idea_added": "{handle}: {text}",
  "stream.idea_removed": "{handle} removed an idea.",
  "stream.vote_cast": "{handle} voted for #{short}.",
  "stream.vote_removed": "{handle} unvoted #{short}.",
  "stream.assessment": "{handle} rated #{short} {kind}: {verdict}{note}",
  "stream.persona_set": "{handle} set persona.{field}: {value}",
  "stream.scope_added": "{handle} +scope.{bucket}: {value}",
  "stream.scope_removed": "{handle} -scope.{bucket}[{n}]",
  "stream.ready_on": "{handle} is ready.",
  "stream.ready_off": "{handle} is not ready.",
  "stream.phase_advanced": "→ phase: {phase}",
  "stream.phase_back_to_brainstorm": "no idea passed the assessment — back to brainstorm.",
  "stream.room_closed": "host closed the room.",

  "phase.brainstorm": "brainstorm",
  "phase.pick_two": "pick two",
  "phase.assess": "assess",
  "phase.pick_winner": "pick winner",
  "phase.persona": "persona",
  "phase.scope": "scope",
  "phase.done": "done",

  "panel.roster": "roster",
  "panel.ideas": "ideas",
  "panel.no_ideas": "(no ideas yet)",
  "panel.votes": "votes",
  "panel.assess": "assessments",
  "panel.persona": "persona",
  "panel.scope": "scope",
  "panel.scope_must": "must",
  "panel.scope_nice": "nice",
  "panel.scope_out": "out",

  "help.header": "commands available in phase: {phase}",
  "help.line.ready": "  ready / not-ready          — toggle your ready flag (quorum advances)",
  "help.line.who": "  who                         — list current participants",
  "help.line.phase": "  phase                       — show phase and quorum",
  "help.line.help": "  help                        — this list",
  "help.line.leave": "  leave                       — leave the room",
  "help.line.close": "  close                       — host only: force the room to done",
  "help.line.clear": "  clear                       — clear the stream",
  "help.line.idea": "  idea <text>                 — add an idea",
  "help.line.idea_rm": "  idea rm <id>                — remove your idea",
  "help.line.vote": "  vote <idea-id>              — cast a vote (2 in pick-two, 1 in pick-winner)",
  "help.line.unvote": "  unvote <idea-id>            — remove your vote",
  "help.line.assess": "  assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "help.line.persona": "  persona who|context|pain <text>",
  "help.line.scope_add": "  scope must|nice|out <text>",
  "help.line.scope_rm": "  scope rm must|nice|out <n>",

  "cmd.error.unknown": "unrecognized command: {cmd}",
  "cmd.error.hint": "type `help` to see what's available.",
  "cmd.error.wrong_phase": "this command isn't available in phase `{phase}`.",
  "cmd.error.idea_required": "idea text required. usage: idea <text>",
  "cmd.error.idea_too_long": "idea text must be 1-280 chars.",
  "cmd.error.idea_not_found": "no idea matches `#{id}`.",
  "cmd.error.idea_not_yours": "you can only remove your own ideas.",
  "cmd.error.idea_limit": "you can post at most 20 ideas per room.",
  "cmd.error.vote_required": "usage: vote <idea-id>",
  "cmd.error.vote_limit": "you've used all your votes for this phase.",
  "cmd.error.vote_invalid": "that idea isn't a candidate in this phase.",
  "cmd.error.unvote_not_found": "you haven't voted on `#{id}`.",
  "cmd.error.assess_usage": "usage: assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "cmd.error.assess_idea_invalid": "that idea isn't in the assess phase.",
  "cmd.error.persona_usage": "usage: persona who|context|pain <text>",
  "cmd.error.scope_usage": "usage: scope <must|nice|out> <text>   or   scope rm <must|nice|out> <n>",
  "cmd.error.scope_index": "scope index out of range.",
  "cmd.error.close_not_host": "only the host can close the room.",
  "cmd.error.network": "request failed: {message}",
  "cmd.success.copied": "brief copied to clipboard.",
  "cmd.success.left": "you left the room.",

  "brief.heading": "═══════════════ BRIEF ═══════════════",
  "brief.winner_label": "🏆  WINNING IDEA",
  "brief.ideas_label": "📋  IDEAS  ({count})",
  "brief.assess_label": "🔬  ASSESSMENT",
  "brief.assess_feasibility": "feasibility",
  "brief.assess_sota": "state of the art",
  "brief.persona_label": "👤  PERSONA",
  "brief.persona_who": "who",
  "brief.persona_context": "context",
  "brief.persona_pain": "pain",
  "brief.scope_label": "🎯  SCOPE",
  "brief.scope_must": "MUST HAVE",
  "brief.scope_nice": "NICE TO HAVE",
  "brief.scope_out": "OUT OF SCOPE",
  "brief.footer": "═════════════════════════════════════",
  "brief.hint_copy": "[c] copy as markdown   [enter] close room",
  "brief.empty": "(nothing here)",
};

const ES: RoomDict = {
  ...EN,
  "title": "sala",
  "subtitle": "brainstorm colaborativo",
  "loading": "cargando sala…",
  "not_found": "sala no encontrada o expirada.",
  "back_to_main": "← volver a /",
  "expired": "esta sala expiró. arrancá una nueva con `room create`.",
  "missing_env": "faltan variables de supabase; las salas no están configuradas.",

  "onboard.heading": "elegí un handle para entrar a la sala.",
  "onboard.handle_prompt": "handle (ej: @aiponce): ",
  "onboard.handle_invalid": "el handle debe tener 2-32 chars (letras/números/_-)",
  "onboard.handle_taken": "ese handle ya está en uso. probá otro.",
  "onboard.cta": "entrar",
  "onboard.share": "compartí este link con tu equipo: {url}",

  "status.phase": "fase: {phase}",
  "status.live": "● en vivo",
  "status.reconnecting": "○ reconectando…",
  "status.expires_in": "expira en {mins}m",
  "status.quorum": "{ready}/{total} listos",
  "status.host": "host",
  "status.expires_soon": "esta sala expira en menos de 15 minutos.",

  "stream.welcome": "bienvenido, {handle}. tipeá `help` para ver comandos.",
  "stream.joined": "{handle} entró.",
  "stream.left": "{handle} salió.",
  "stream.idea_added": "{handle}: {text}",
  "stream.idea_removed": "{handle} borró una idea.",
  "stream.vote_cast": "{handle} votó #{short}.",
  "stream.vote_removed": "{handle} sacó el voto a #{short}.",
  "stream.assessment": "{handle} evaluó #{short} {kind}: {verdict}{note}",
  "stream.persona_set": "{handle} setteó persona.{field}: {value}",
  "stream.scope_added": "{handle} +scope.{bucket}: {value}",
  "stream.scope_removed": "{handle} -scope.{bucket}[{n}]",
  "stream.ready_on": "{handle} listo.",
  "stream.ready_off": "{handle} no listo.",
  "stream.phase_advanced": "→ fase: {phase}",
  "stream.phase_back_to_brainstorm": "ninguna idea pasó el assessment — volvemos a brainstorm.",
  "stream.room_closed": "el host cerró la sala.",

  "phase.brainstorm": "brainstorm",
  "phase.pick_two": "elegir 2",
  "phase.assess": "evaluar",
  "phase.pick_winner": "elegir ganadora",
  "phase.persona": "persona",
  "phase.scope": "scope",
  "phase.done": "fin",

  "panel.roster": "equipo",
  "panel.ideas": "ideas",
  "panel.no_ideas": "(sin ideas aún)",
  "panel.votes": "votos",
  "panel.assess": "evaluaciones",
  "panel.persona": "persona",
  "panel.scope": "scope",
  "panel.scope_must": "must",
  "panel.scope_nice": "nice",
  "panel.scope_out": "out",

  "help.header": "comandos disponibles en fase: {phase}",
  "help.line.ready": "  ready / not-ready          — togglear tu flag (el quórum avanza la fase)",
  "help.line.who": "  who                         — listar participantes",
  "help.line.phase": "  phase                       — mostrar fase y quórum",
  "help.line.help": "  help                        — esta lista",
  "help.line.leave": "  leave                       — salir de la sala",
  "help.line.close": "  close                       — solo host: forzar fase done",
  "help.line.clear": "  clear                       — limpiar el stream",
  "help.line.idea": "  idea <texto>                — agregar una idea",
  "help.line.idea_rm": "  idea rm <id>                — borrar tu propia idea",
  "help.line.vote": "  vote <idea-id>              — votar (2 en elegir-2, 1 en elegir-ganadora)",
  "help.line.unvote": "  unvote <idea-id>            — sacar tu voto",
  "help.line.assess": "  assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "help.line.persona": "  persona who|context|pain <texto>",
  "help.line.scope_add": "  scope must|nice|out <texto>",
  "help.line.scope_rm": "  scope rm must|nice|out <n>",

  "cmd.error.unknown": "comando no reconocido: {cmd}",
  "cmd.error.hint": "tipeá `help` para ver qué hay disponible.",
  "cmd.error.wrong_phase": "este comando no está disponible en la fase `{phase}`.",
  "cmd.error.idea_required": "falta el texto. uso: idea <texto>",
  "cmd.error.idea_too_long": "el texto debe tener 1-280 chars.",
  "cmd.error.idea_not_found": "no hay idea con `#{id}`.",
  "cmd.error.idea_not_yours": "solo podés borrar tus propias ideas.",
  "cmd.error.idea_limit": "podés postear como máximo 20 ideas por sala.",
  "cmd.error.vote_required": "uso: vote <idea-id>",
  "cmd.error.vote_limit": "ya usaste todos tus votos en esta fase.",
  "cmd.error.vote_invalid": "esa idea no es candidata en esta fase.",
  "cmd.error.unvote_not_found": "no votaste por `#{id}`.",
  "cmd.error.assess_usage": "uso: assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "cmd.error.assess_idea_invalid": "esa idea no está en la fase de assess.",
  "cmd.error.persona_usage": "uso: persona who|context|pain <texto>",
  "cmd.error.scope_usage": "uso: scope <must|nice|out> <texto>   o   scope rm <must|nice|out> <n>",
  "cmd.error.scope_index": "índice de scope fuera de rango.",
  "cmd.error.close_not_host": "solo el host puede cerrar la sala.",
  "cmd.error.network": "falló el request: {message}",
  "cmd.success.copied": "brief copiado al portapapeles.",
  "cmd.success.left": "saliste de la sala.",

  "brief.heading": "═══════════════ BRIEF ═══════════════",
  "brief.winner_label": "🏆  IDEA GANADORA",
  "brief.ideas_label": "📋  IDEAS  ({count})",
  "brief.assess_label": "🔬  EVALUACIÓN",
  "brief.assess_feasibility": "factibilidad",
  "brief.assess_sota": "estado del arte",
  "brief.persona_label": "👤  PERSONA",
  "brief.persona_who": "quién",
  "brief.persona_context": "contexto",
  "brief.persona_pain": "dolor",
  "brief.scope_label": "🎯  SCOPE",
  "brief.scope_must": "MUST HAVE",
  "brief.scope_nice": "NICE TO HAVE",
  "brief.scope_out": "OUT OF SCOPE",
  "brief.footer": "═════════════════════════════════════",
  "brief.hint_copy": "[c] copiar como markdown   [enter] cerrar sala",
  "brief.empty": "(vacío)",
};

const PT: RoomDict = {
  ...EN,
  "title": "sala",
  "subtitle": "brainstorm colaborativo",
  "loading": "carregando sala…",
  "not_found": "sala não encontrada ou expirada.",
  "back_to_main": "← voltar para /",
  "expired": "esta sala expirou. comece uma nova com `room create`.",
  "missing_env": "variáveis do supabase faltando; salas não estão configuradas.",

  "onboard.heading": "escolha um handle para entrar na sala.",
  "onboard.handle_prompt": "handle (ex: @aiponce): ",
  "onboard.handle_invalid": "o handle deve ter 2-32 chars (letras/números/_-)",
  "onboard.handle_taken": "esse handle já está em uso. tente outro.",
  "onboard.cta": "entrar",
  "onboard.share": "compartilhe este link com seu time: {url}",

  "status.phase": "fase: {phase}",
  "status.live": "● ao vivo",
  "status.reconnecting": "○ reconectando…",
  "status.expires_in": "expira em {mins}m",
  "status.quorum": "{ready}/{total} prontos",
  "status.host": "host",
  "status.expires_soon": "esta sala expira em menos de 15 minutos.",

  "stream.welcome": "bem-vindo, {handle}. digite `help` para ver os comandos.",
  "stream.joined": "{handle} entrou.",
  "stream.left": "{handle} saiu.",
  "stream.idea_added": "{handle}: {text}",
  "stream.idea_removed": "{handle} removeu uma ideia.",
  "stream.vote_cast": "{handle} votou em #{short}.",
  "stream.vote_removed": "{handle} removeu o voto em #{short}.",
  "stream.assessment": "{handle} avaliou #{short} {kind}: {verdict}{note}",
  "stream.persona_set": "{handle} definiu persona.{field}: {value}",
  "stream.scope_added": "{handle} +scope.{bucket}: {value}",
  "stream.scope_removed": "{handle} -scope.{bucket}[{n}]",
  "stream.ready_on": "{handle} pronto.",
  "stream.ready_off": "{handle} não pronto.",
  "stream.phase_advanced": "→ fase: {phase}",
  "stream.phase_back_to_brainstorm": "nenhuma ideia passou na avaliação — voltamos ao brainstorm.",
  "stream.room_closed": "o host fechou a sala.",

  "phase.brainstorm": "brainstorm",
  "phase.pick_two": "escolher 2",
  "phase.assess": "avaliar",
  "phase.pick_winner": "escolher vencedora",
  "phase.persona": "persona",
  "phase.scope": "escopo",
  "phase.done": "fim",

  "panel.roster": "time",
  "panel.ideas": "ideias",
  "panel.no_ideas": "(sem ideias ainda)",
  "panel.votes": "votos",
  "panel.assess": "avaliações",
  "panel.persona": "persona",
  "panel.scope": "escopo",
  "panel.scope_must": "must",
  "panel.scope_nice": "nice",
  "panel.scope_out": "out",

  "help.header": "comandos disponíveis na fase: {phase}",
  "help.line.ready": "  ready / not-ready          — alternar seu flag (o quorum avança)",
  "help.line.who": "  who                         — listar participantes",
  "help.line.phase": "  phase                       — mostrar fase e quorum",
  "help.line.help": "  help                        — esta lista",
  "help.line.leave": "  leave                       — sair da sala",
  "help.line.close": "  close                       — só host: forçar fase done",
  "help.line.clear": "  clear                       — limpar o stream",
  "help.line.idea": "  idea <texto>                — adicionar uma ideia",
  "help.line.idea_rm": "  idea rm <id>                — remover sua ideia",
  "help.line.vote": "  vote <idea-id>              — votar (2 em pick-two, 1 em pick-winner)",
  "help.line.unvote": "  unvote <idea-id>            — remover seu voto",
  "help.line.assess": "  assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "help.line.persona": "  persona who|context|pain <texto>",
  "help.line.scope_add": "  scope must|nice|out <texto>",
  "help.line.scope_rm": "  scope rm must|nice|out <n>",

  "cmd.error.unknown": "comando não reconhecido: {cmd}",
  "cmd.error.hint": "digite `help` para ver o que está disponível.",
  "cmd.error.wrong_phase": "este comando não está disponível na fase `{phase}`.",
  "cmd.error.idea_required": "falta o texto. uso: idea <texto>",
  "cmd.error.idea_too_long": "o texto deve ter 1-280 chars.",
  "cmd.error.idea_not_found": "não há ideia com `#{id}`.",
  "cmd.error.idea_not_yours": "você só pode remover suas próprias ideias.",
  "cmd.error.idea_limit": "máx 20 ideias por sala.",
  "cmd.error.vote_required": "uso: vote <idea-id>",
  "cmd.error.vote_limit": "você já usou todos os votos desta fase.",
  "cmd.error.vote_invalid": "essa ideia não é candidata nesta fase.",
  "cmd.error.unvote_not_found": "você não votou em `#{id}`.",
  "cmd.error.assess_usage": "uso: assess <idea-id> <feasibility|sota> <yes|no|maybe> [--note \"...\"]",
  "cmd.error.assess_idea_invalid": "essa ideia não está na fase de avaliação.",
  "cmd.error.persona_usage": "uso: persona who|context|pain <texto>",
  "cmd.error.scope_usage": "uso: scope <must|nice|out> <texto>   ou   scope rm <must|nice|out> <n>",
  "cmd.error.scope_index": "índice de scope fora do alcance.",
  "cmd.error.close_not_host": "só o host pode fechar a sala.",
  "cmd.error.network": "request falhou: {message}",
  "cmd.success.copied": "brief copiado para a área de transferência.",
  "cmd.success.left": "você saiu da sala.",

  "brief.heading": "═══════════════ BRIEF ═══════════════",
  "brief.winner_label": "🏆  IDEIA VENCEDORA",
  "brief.ideas_label": "📋  IDEIAS  ({count})",
  "brief.assess_label": "🔬  AVALIAÇÃO",
  "brief.assess_feasibility": "viabilidade",
  "brief.assess_sota": "estado da arte",
  "brief.persona_label": "👤  PERSONA",
  "brief.persona_who": "quem",
  "brief.persona_context": "contexto",
  "brief.persona_pain": "dor",
  "brief.scope_label": "🎯  ESCOPO",
  "brief.scope_must": "MUST HAVE",
  "brief.scope_nice": "NICE TO HAVE",
  "brief.scope_out": "OUT OF SCOPE",
  "brief.footer": "═════════════════════════════════════",
  "brief.hint_copy": "[c] copiar como markdown   [enter] fechar sala",
  "brief.empty": "(vazio)",
};

const DICTS: Record<Locale, RoomDict> = { en: EN, es: ES, pt: PT };

export function loadRoomDict(locale: Locale): RoomDict {
  return DICTS[locale] ?? EN;
}

export function makeT(dict: RoomDict) {
  return function t(key: string, vars?: Record<string, string | number>): string {
    const val = dict[key];
    if (typeof val !== "string") return key;
    if (!vars) return val;
    return val.replace(/\{(\w+)\}/g, (_m, k) =>
      vars[k] !== undefined && vars[k] !== null ? String(vars[k]) : ""
    );
  };
}
